### ISSUE TITLE
Add a function to create a JAR.

### ISSUE THREAD

**Issue by skleinei** [K15t/gulp-viewport#1]
As discussed on the google group it would be pretty great to have a function to create a JAR: https://groups.google.com/d/msgid/scroll-viewport-dev/6e628404-064a-423f-b517-8a62f3735363%40googlegroups.com

**Comment by jensrutschmann** [comment]
Closing because this repo is deprecated and will now be archived.
Please use https://github.com/K15t/viewport-uploader instead.
