### ISSUE TITLE
Add API to create a Viewport

### ISSUE THREAD

**Issue by skleinei** [K15t/gulp-viewport#17]
It'd be great if we could create a viewport with the gulp-viewport plugin.

Things to discuss:
* what should gulp-viewport do, if the space is not available?
* can gulp-viewport also create sample content?

**Comment by SteBurz** [comment]
If the space is not available it should be asked if it should be created.

It would also be nice, if you could activate a viewport with the created space. Something like:
`gulp activate spaceKey`

**Comment by jensrutschmann** [comment]
Closing because this repo is deprecated and will now be archived.
Please use https://github.com/K15t/viewport-uploader instead.
