### ISSUE TITLE
Support Gulp 4

### ISSUE THREAD

**Issue by rikuhaa** [K15t/gulp-viewport#20]
We should update gulp-viewport to support Gulp 4:

- Update the documentation and examples to show how gulp-viewport can be used with Gulp 4

- Test with Gulp 4 to see if some code changes are needed

**Comment by seona13** [comment]
I can tell you for a fact that code changes will be needed. It doesn't work as is.

**Comment by jensrutschmann** [comment]
Closing because this repo is deprecated and will now be archived.
Please use https://github.com/K15t/viewport-uploader instead.
