### ISSUE TITLE
Upload "kills" Theme

### ISSUE THREAD

**Issue by omphteliba** [K15t/gulp-viewport#5]
Uploading anything else than the *.vm files in the base folder kills the theme. It is still in the list of viewport themes, but when I try to edit it, i get an error saying "could not load theme".

**Comment by MartinMuzatko** [comment]
Hello @omphteliba. Can you please let me know what version of Scroll Viewport and Confluence are you using?

If you download the theme as jar, and then unzip it - does it contain any malformed code?
How did you name the theme?
Themes fail to load when the webresource for the following URL can't be found.
These strings are concatenated, so maybe there is an issue with the naming:
CONTEXT_URL,BASE_THEME_URL, '/theme/',THEME_ID

Thank you in advance!

**Comment by omphteliba** [comment]
Hej Martin,
thanks for your feedback!
we are using Scroll Viewport v 2.5.0 with Confluence 5.10.8, and the name of the theme is "FACT-Finder-MAR". 

The JAR after I can't load it anymore, looks ok to me (see attachment).

[fact-finder-mar-1.0.jar.zip](https://github.com/K15t/gulp-viewport/files/734984/fact-finder-mar-1.0.jar.zip)

It's not the upload that isn't working, after I uploaded it, I can't edit it confluence.

Here is the gulp log from the task upload:

> "C:\Program Files (x86)\JetBrains\PhpStorm 2016.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\node_modules\gulp\bin\gulp.js --color --gulpfile Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\gulpfile.js upload
> 
> ======================================================
>    You are deploying 'FACT-Finder-MAR'to:
>    https://dokuext.omikron.net
> ======================================================
> 
> [11:45:15] Using gulpfile Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\gulpfile.js
> [11:45:15] Starting 'fonts'...
> [11:45:15] Starting 'img'...
> [11:45:15] Starting 'js'...
> [11:45:15] Starting 'less'...
> [11:45:15] Starting 'templates'...
> [11:45:15] Finished 'less' after 18 ms
> [11:45:15] Finished 'templates' after 24 ms
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\atlassian-icons.eot' to 'fonts\atlassian-icons.eot'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\img\logo_background.png' to 'img\logo_background.png'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\jquery.min.js' to 'js\jquery.min.js'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\atlassian-icons.svg' to 'fonts\atlassian-icons.svg'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\img\logo_fact-finder.png' to 'img\logo_fact-finder.png'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\jquery.scroll-tree.js' to 'js\jquery.scroll-tree.js'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\atlassian-icons.ttf' to 'fonts\atlassian-icons.ttf'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\jquery.scrollTo.min.js' to 'js\jquery.scrollTo.min.js'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\atlassian-icons.woff' to 'fonts\atlassian-icons.woff'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\prism.js' to 'js\prism.js'.
> [11:45:15] Finished 'img' after 127 ms
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\k15t-icons.eot' to 'fonts\k15t-icons.eot'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\scroll-search.js' to 'js\scroll-search.js'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\k15t-icons.svg' to 'fonts\k15t-icons.svg'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\scroll-tree.js' to 'js\scroll-tree.js'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\k15t-icons.ttf' to 'fonts\k15t-icons.ttf'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\js\theme.main.js' to 'js\theme.main.js'.
> Uploading 'Z:\01_Projects\02_Small-scale_Projects\20170126_FF_Dokuportal_Support\technik\assets\fonts\k15t-icons.woff' to 'fonts\k15t-icons.woff'.
> [11:45:15] Finished 'js' after 188 ms
> [11:45:15] Finished 'fonts' after 220 ms
> [11:45:15] Starting 'upload'...
> [11:45:15] Finished 'upload' after 14 μs
> File 'logo_background.png' successfully uploaded.
> File 'atlassian-icons.eot' successfully uploaded.
> File 'jquery.scrollTo.min.js' successfully uploaded.
> File 'logo_fact-finder.png' successfully uploaded.
> File 'jquery.min.js' successfully uploaded.
> File 'atlassian-icons.ttf' successfully uploaded.
> File 'jquery.scroll-tree.js' successfully uploaded.
> File 'scroll-tree.js' successfully uploaded.
> File 'prism.js' successfully uploaded.
> File 'scroll-search.js' successfully uploaded.
> File 'k15t-icons.eot' successfully uploaded.
> File 'k15t-icons.woff' successfully uploaded.
> File 'theme.main.js' successfully uploaded.
> File 'k15t-icons.ttf' successfully uploaded.
> File 'k15t-icons.svg' successfully uploaded.
> File 'atlassian-icons.woff' successfully uploaded.
> File 'atlassian-icons.svg' successfully uploaded.
> 
> Process finished with exit code 0

**Comment by MartinMuzatko** [comment]
This looks weird - your files are duplicated with a slash in the filename. See image:
![image](https://cloud.githubusercontent.com/assets/2950505/22375917/4643a160-e4ac-11e6-96ba-62e5ebd0b4fc.png)

Can you share your gulpfile.js with me please?

**Comment by omphteliba** [comment]
Here you go:
[gulpfile.zip](https://github.com/K15t/gulp-viewport/files/735581/gulpfile.zip)

Did I maybe setup the dev folder in the wrong way? This is how it looks like

![dev_folder](https://cloud.githubusercontent.com/assets/196336/22376279/a3d05570-e4ad-11e6-8cb5-c6a45fa13d1c.jpg)

**Comment by MartinMuzatko** [comment]
Hello @omphteliba.
We decided to deal with this issue within our support channel. I sent you an email a minute ago.
Thank you in advance.

**Comment by omphteliba** [comment]
Ok, thanks Martin. I received the emails.
